### ISSUE TITLE
storing tokens in yaml config

### ISSUE THREAD

**Issue by grahamlopez** [adam-mcdaniel/rusty-ci#47]
we need to find a way to protect the API tokens that are currently stored in the yaml config, so that we can actually store the yaml config with the source code in its repo

**Comment by grahamlopez** [comment]
let's not store in yaml, but have

`rusty-ci build myconfig.yaml`
output a message at the end that explains where to add the token, and then the command to start up buildbot

**Comment by adam-mcdaniel** [comment]
Now it outputs a message telling the user to put the token in a file named `auth.token`. Then the token is inserted where it needs to be during the build step.
