### ISSUE TITLE
update commit status on github

### ISSUE THREAD

**Issue by grahamlopez** [adam-mcdaniel/rusty-ci#49]
use the "repo" permissions in a github api token to update the commit status with "waiting, inprogress, failed, success, etc."

**Comment by adam-mcdaniel** [comment]
I've just added minimal support for pushing commit status, tomorrow ill implement the "waiting, in progress, failed, success" messages

**Comment by grahamlopez** [comment]
note that those are not messages, they are commit statuses supported by the github API.

See the "state" parameter here: https://developer.github.com/v3/repos/statuses/

**Comment by adam-mcdaniel** [comment]
This is what the commit status looks before I've added any descriptions to it. It's somewhat hard to tell what buildbot is doing in the background when I added the `GitHubStatusPush` service, but as far as I can tell, this is what you had in mind. https://github.com/adam-mcdaniel/carbon/pull/13

**Comment by adam-mcdaniel** [comment]
In the docs it does say that the `GitHubStatusPush` object does use the GitHub status api

**Comment by adam-mcdaniel** [comment]
Fixed by #55
