### ISSUE TITLE
allow whitelisted users to okay a pull request for testing

### ISSUE THREAD

**Issue by grahamlopez** [adam-mcdaniel/rusty-ci#50]
the bot should indicate when it needs permission from a ci-defined admin to proceed, and then proceed when an appropriate comment is placed on the PR

**Comment by adam-mcdaniel** [comment]
In the `password` subsection of the `merge-request-handler` definition, you can put a regular expression to match comments made by a whitelisted user that will whitelist the PR number for testing.
